### ISSUE TITLE
Ingredient's resource "swarms" field is always an empty list. 

### ISSUE THREAD

**Issue by mnowotka** [yougov/vr.server#2]
Hi,

If you check `/api/v1/ingredients/18/?format=json` you will notice a `swarms` field. It seems that this field is intended to show all swarms related to a given ingredient but it doesn't work this way. 

VR HTTP interface (`/ingredient/18/`) corresponding to the API shows multiple swarms using this ingredient.

**Comment by lbolla** [comment]
Fixed in https://github.com/yougov/vr.server/commit/8561f797b89a19bd5eb9aad3b019606aa815081b

**Comment by mnowotka** [comment]
Thanks a lot!
